# Generated by Django 5.0.4 on 2024-05-03 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactform",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
