# Generated by Django 5.0.4 on 2024-05-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0002_contactform_date_created"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactForm",
            new_name="Comment",
        ),
    ]
