# Generated by Django 5.0.6 on 2024-05-10 20:48

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0006_alter_comment_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
